# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='来源链接')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('hot_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='热度分数')),
                ('rank_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='榜单类型')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '创意',
                'verbose_name_plural': '创意',
                'db_table': 'inspiration',
                'ordering': ['-hot_score', '-collected_at'],
                'indexes': [models.Index(fields=['is_used', '-hot_score'], name='inspiration_is_used_f5609a_idx'), models.Index(fields=['-collected_at'], name='inspiration_collect_0d1e3c_idx')],
            },
        ),
    ]
