# Generated by Django 4.2.11 on 2026-04-08 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0002_initial'),
        ('chapters', '0004_chapter_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_username', models.CharField(max_length=100, verbose_name='平台用户名')),
                ('platform_password', models.CharField(max_length=255, verbose_name='平台密码（加密）')),
                ('novel_id', models.CharField(help_text='番茄小说平台的小说ID', max_length=100, verbose_name='小说ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('proxy_list', models.TextField(blank=True, help_text='每行一个代理，格式：http://ip:port', verbose_name='代理IP列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_configs', to='novels.novelproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '发布配置',
                'verbose_name_plural': '发布配置',
                'db_table': 'publish_config',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='PublishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待发布'), ('publishing', '发布中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20)),
                ('platform_chapter_id', models.CharField(blank=True, max_length=100, verbose_name='平台章节ID')),
                ('error_message', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_records', to='chapters.chapter')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_records', to='publishing.publishconfig')),
            ],
            options={
                'verbose_name': '发布记录',
                'verbose_name_plural': '发布记录',
                'db_table': 'publish_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
