# Generated by Django 4.2.11 on 2026-04-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishconfig',
            name='platform_password',
        ),
        migrations.AddField(
            model_name='publishconfig',
            name='_platform_password_encrypted',
            field=models.TextField(db_column='platform_password', default='', verbose_name='平台密码（加密）'),
        ),
    ]
