# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('qwen', '通义千问'), ('custom', '自定义')], max_length=20, verbose_name='服务类型')),
                ('api_url', models.URLField(max_length=255, verbose_name='API 地址')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('task_type', models.CharField(choices=[('idea_generation', '创意生成'), ('chapter_writing', '章节写作')], max_length=20, verbose_name='任务类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM 服务提供商',
                'verbose_name_plural': 'LLM 服务提供商',
                'db_table': 'llm_provider',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
