# Generated by Django 4.2.11 on 2026-04-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_providers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmprovider',
            name='api_key',
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='_api_key_encrypted',
            field=models.TextField(db_column='api_key', default='', verbose_name='API Key (加密)'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('tongyi', '通义千问'), ('custom', '自定义')], max_length=20, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='task_type',
            field=models.CharField(choices=[('outline', '大纲生成'), ('chapter', '章节生成'), ('continue', '内容续写')], max_length=20, verbose_name='任务类型'),
        ),
    ]
