# Generated by Django 4.2.11 on 2026-04-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_providers', '0003_remove_llmprovider_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', help_text='例如: gpt-3.5-turbo, qwen-turbo, qwen-plus', max_length=100, verbose_name='模型名称'),
        ),
    ]
