# Generated by Django 4.2.11 on 2026-04-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_providers', '0004_llmprovider_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='task_type',
            field=models.CharField(choices=[('outline', '大纲生成'), ('chapter', '章节生成'), ('continue', '内容续写'), ('setting', '设定生成')], max_length=20, verbose_name='任务类型'),
        ),
    ]
