from datetime import datetime, time

from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.dateparse import parse_date, parse_datetime
from rest_framework import serializers, status, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import ValidationError
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.authentication import JWTAuthentication

from apps.chapters.models import Chapter, ChapterReview, ChapterSummary
from apps.chapters.serializers import ChapterReviewSerializer, ChapterSerializer
from apps.chapters.services.review import build_ai_review_payload, sync_chapter_review
from apps.chapters.services.workflow import (
    MIN_MANUAL_MODIFICATION_RATE,
    refresh_chapter_workflow_assets,
)
from apps.novels.models import NovelProject
from apps.tasks.models import Task
from celery_tasks.ai_tasks import generate_chapter_async
from celery_tasks.publish_tasks import publish_chapter_async

PUBLISH_STATUS_TO_INTERNAL = {
    'draft': ('generating', 'draft'),
    'published': ('published',),
    'failed': ('failed',),
}

FULL_AUTO_REVIEW_NOTE = '全自动模式：本章由托管流程自动审定，跳过人工审阅。'


def _is_full_auto_chapter(chapter):
    """Return whether a chapter was generated by the full-auto review policy."""
    generation_meta = chapter.generation_meta or {}
    context_snapshot = chapter.context_snapshot or {}
    return bool(
        generation_meta.get('full_auto_mode')
        or generation_meta.get('auto_review_skipped')
        or context_snapshot.get('full_auto_mode')
    )


class ChapterViewSet(viewsets.ModelViewSet):
    """CRUD API for chapters scoped to the authenticated user's projects."""

    serializer_class = ChapterSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAuthenticated,)

    def _parse_datetime_query_param(self, param_name, default_time):
        """Parse datetime/date query values into timezone-aware datetimes."""
        raw_value = self.request.query_params.get(param_name)
        if not raw_value:
            return None

        parsed_value = parse_datetime(raw_value)
        if parsed_value is None:
            parsed_date = parse_date(raw_value)
            if parsed_date is not None:
                parsed_value = datetime.combine(parsed_date, default_time)

        if parsed_value is None:
            raise ValidationError(
                {param_name: 'Use ISO 8601 datetime or YYYY-MM-DD format.'}
            )

        if timezone.is_naive(parsed_value):
            parsed_value = timezone.make_aware(
                parsed_value,
                timezone.get_current_timezone(),
            )

        return parsed_value

    def get_queryset(self):
        """Return filtered chapters owned by the current authenticated user."""
        queryset = (
            Chapter.objects.select_related(
                'project',
                'project__user',
                'llm_provider',
                'review_record',
            )
            .filter(
                project__user=self.request.user,
                project__is_deleted=False,
                is_deleted=False,
            )
            .order_by('-created_at')
        )

        project_id = self.request.query_params.get('project_id', '').strip()
        if project_id:
            if not project_id.isdigit():
                raise ValidationError({'project_id': 'project_id must be a positive integer.'})
            queryset = queryset.filter(project_id=int(project_id))

        publish_status_filter = self.request.query_params.get('publish_status', '').strip()
        if publish_status_filter:
            publish_statuses = [
                value.strip() for value in publish_status_filter.split(',') if value.strip()
            ]
            unknown_statuses = [
                status for status in publish_statuses if status not in PUBLISH_STATUS_TO_INTERNAL
            ]
            if unknown_statuses:
                raise ValidationError(
                    {'publish_status': f'Unsupported values: {", ".join(unknown_statuses)}.'}
                )

            internal_statuses = []
            for status in publish_statuses:
                internal_statuses.extend(PUBLISH_STATUS_TO_INTERNAL[status])
            queryset = queryset.filter(status__in=internal_statuses)

        title_keyword = (
            self.request.query_params.get('search')
            or self.request.query_params.get('title')
            or ''
        ).strip()
        if title_keyword:
            queryset = queryset.filter(Q(title__icontains=title_keyword))

        created_after = self._parse_datetime_query_param('created_after', time.min)
        if created_after is None:
            created_after = self._parse_datetime_query_param('created_from', time.min)

        created_before = self._parse_datetime_query_param('created_before', time.max)
        if created_before is None:
            created_before = self._parse_datetime_query_param('created_to', time.max)

        if created_after and created_before and created_after > created_before:
            raise ValidationError(
                {'created_after': 'created_after must be earlier than created_before.'}
            )

        if created_after:
            queryset = queryset.filter(created_at__gte=created_after)
        if created_before:
            queryset = queryset.filter(created_at__lte=created_before)

        return queryset

    def perform_destroy(self, instance):
        """Soft delete the chapter instead of removing the row."""
        instance.is_deleted = True
        instance.save(update_fields=['is_deleted', 'updated_at'])

    def perform_create(self, serializer):
        """Create chapter and initialize review workflow metadata."""
        chapter = serializer.save()
        if chapter.raw_content or chapter.final_content:
            content = chapter.final_content or chapter.raw_content or ''
            refresh_chapter_workflow_assets(chapter.project, chapter, content)
            review = sync_chapter_review(
                chapter,
                reviewer=self.request.user,
                refresh_ai=True,
                reset_status=True,
            )
            chapter.review_record = review

    def perform_update(self, serializer):
        """Keep review workflow in sync when chapter content changes."""
        instance = serializer.instance
        previous_raw = instance.raw_content
        previous_final = instance.final_content
        chapter = serializer.save()

        content_changed = (
            previous_raw != chapter.raw_content
            or previous_final != chapter.final_content
        )
        if content_changed:
            content = chapter.final_content or chapter.raw_content or ''
            refresh_chapter_workflow_assets(chapter.project, chapter, content)
            review = sync_chapter_review(
                chapter,
                reviewer=self.request.user,
                refresh_ai=True,
                reset_status=True,
            )
            chapter.review_record = review

    @action(detail=True, methods=['post'], url_path='publish')
    def publish(self, request, pk=None):
        """Publish a chapter to Tomato Novel platform."""
        chapter = self.get_object()
        review = getattr(chapter, 'review_record', None)

        # Check if chapter is in draft status (ready to publish)
        if chapter.status != 'draft':
            return Response(
                {'error': 'Chapter must be in draft status before publishing. Current status: ' + chapter.status},
                status=status.HTTP_400_BAD_REQUEST
            )
        if not review or review.status != 'approved':
            return Response(
                {'error': 'Chapter must be approved in review before publishing.'},
                status=status.HTTP_400_BAD_REQUEST
            )
        if (
            not _is_full_auto_chapter(chapter)
            and (review.modification_rate or 0) < MIN_MANUAL_MODIFICATION_RATE
        ):
            return Response(
                {
                    'error': (
                        f'Chapter modification rate must be at least {MIN_MANUAL_MODIFICATION_RATE}% '
                        'before publishing.'
                    ),
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        # Create task record
        task_record = Task.objects.create(
            task_type='publish_chapter',
            related_type='chapter',
            related_id=chapter.id,
            status='pending',
            params={
                'chapter_id': chapter.id,
                'project_id': chapter.project.id,
            },
        )

        # Trigger async publish task
        async_result = publish_chapter_async.delay(
            chapter.id,
            task_record_id=task_record.id,
        )
        task_record.celery_task_id = async_result.id
        task_record.save(update_fields=['celery_task_id', 'updated_at'])

        return Response(
            {
                'task_id': async_result.id,
                'task_record_id': task_record.id,
                'status': task_record.status,
                'message': 'Chapter publishing task started',
            },
            status=status.HTTP_202_ACCEPTED,
        )

    @action(detail=True, methods=['get', 'post'], url_path='review')
    def review(self, request, pk=None):
        """Read or upsert the review record for a chapter."""
        chapter = self.get_object()
        review, _created = ChapterReview.objects.get_or_create(
            project=chapter.project,
            chapter=chapter,
            defaults={'reviewer': request.user},
        )

        if request.method.lower() == 'get':
            return Response(ChapterReviewSerializer(review).data)

        class ChapterReviewRequestSerializer(serializers.Serializer):
            status = serializers.ChoiceField(
                choices=['pending', 'approved', 'revise'],
                required=False,
            )
            review_notes = serializers.CharField(required=False, allow_blank=True)
            generate_ai = serializers.BooleanField(required=False, default=False)
            apply_ai_to_notes = serializers.BooleanField(required=False, default=False)

        serializer = ChapterReviewRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        review.reviewer = request.user
        should_update_chapter_reviewed_at = False

        if serializer.validated_data.get('generate_ai'):
            ai_payload = build_ai_review_payload(chapter)
            review.ai_review = ai_payload['ai_review']
            review.ai_action_items = ai_payload['ai_action_items']
            review.modification_rate = ai_payload['modification_rate']
            review.ai_generated_at = timezone.now()

        if 'review_notes' in serializer.validated_data:
            review.review_notes = serializer.validated_data['review_notes']
            should_update_chapter_reviewed_at = True

        if serializer.validated_data.get('apply_ai_to_notes') and review.ai_review:
            review.review_notes = review.ai_review
            should_update_chapter_reviewed_at = True

        if 'status' in serializer.validated_data:
            review.status = serializer.validated_data['status']
            should_update_chapter_reviewed_at = review.status in ('approved', 'revise')

        if not review.modification_rate:
            review.modification_rate = build_ai_review_payload(chapter)['modification_rate']

        requested_status = serializer.validated_data.get('status')
        if requested_status == 'approved' and review.modification_rate < MIN_MANUAL_MODIFICATION_RATE:
            return Response(
                {
                    'error': (
                        f'人工改稿幅度低于 {MIN_MANUAL_MODIFICATION_RATE}% ，'
                        '当前章节不能标记为已定稿。'
                    ),
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        review.save()

        if should_update_chapter_reviewed_at:
            chapter.reviewed_at = timezone.now()
            chapter.save(update_fields=['reviewed_at', 'updated_at'])
        elif review.status == 'pending' and not review.review_notes.strip():
            if chapter.reviewed_at is not None:
                chapter.reviewed_at = None
                chapter.save(update_fields=['reviewed_at', 'updated_at'])

        return Response(ChapterReviewSerializer(review).data)


class ChapterGenerateAsyncRequestSerializer(serializers.Serializer):
    """Payload schema for async chapter generation endpoint."""

    project_id = serializers.IntegerField(min_value=1)
    chapter_number = serializers.IntegerField(min_value=1)
    chapter_title = serializers.CharField(max_length=200)


class GenerateFromWSRequestSerializer(serializers.Serializer):
    """Payload schema for the Django callback used by WebSocket generation."""

    project_id = serializers.IntegerField(min_value=1)
    chapter_number = serializers.IntegerField(min_value=1)
    chapter_title = serializers.CharField(max_length=200, required=False, allow_blank=True)
    content = serializers.CharField(allow_blank=True)
    word_count = serializers.IntegerField(min_value=0, required=False, default=0)
    generation_meta = serializers.JSONField(required=False)
    context_snapshot = serializers.JSONField(required=False)


class ChapterGenerateAsyncView(APIView):
    """Trigger async chapter generation task via Celery."""

    permission_classes = (IsAuthenticated,)

    def post(self, request, *args, **kwargs):
        serializer = ChapterGenerateAsyncRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        project_id = serializer.validated_data['project_id']
        chapter_number = serializer.validated_data['chapter_number']
        chapter_title = serializer.validated_data['chapter_title']

        project = get_object_or_404(
            NovelProject,
            id=project_id,
            user=request.user,
            is_deleted=False,
        )

        task_record = Task.objects.create(
            task_type='generate_chapter',
            related_type='project',
            related_id=project.id,
            status='pending',
            params={
                'project_id': project.id,
                'chapter_number': chapter_number,
                'chapter_title': chapter_title,
            },
        )

        async_result = generate_chapter_async.delay(
            project.id,
            chapter_number,
            chapter_title,
            task_record_id=task_record.id,
        )
        task_record.celery_task_id = async_result.id
        task_record.save(update_fields=['celery_task_id', 'updated_at'])

        return Response(
            {
                'task_id': async_result.id,
                'task_record_id': task_record.id,
                'status': task_record.status,
            },
            status=status.HTTP_202_ACCEPTED,
        )


class GenerateFromWSView(APIView):
    """Called by FastAPI WebSocket handler to save a generated chapter as draft."""
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        from django.db import transaction

        serializer = GenerateFromWSRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        project_id = serializer.validated_data['project_id']
        chapter_number = serializer.validated_data['chapter_number']
        chapter_title = serializer.validated_data.get('chapter_title') or f'第{chapter_number}章'
        content = serializer.validated_data.get('content', '')
        word_count = serializer.validated_data.get('word_count') or len(
            [char for char in content if not char.isspace()]
        )
        generation_meta = serializer.validated_data.get('generation_meta') or {}
        context_snapshot = serializer.validated_data.get('context_snapshot') or {}
        full_auto_mode = bool(
            generation_meta.get('full_auto_mode')
            or context_snapshot.get('full_auto_mode')
        )
        if full_auto_mode:
            generation_meta = {
                **generation_meta,
                'full_auto_mode': True,
                'auto_review_skipped': True,
                'review_strategy': 'full_auto_auto_approved',
            }
            context_snapshot = {
                **context_snapshot,
                'full_auto_mode': True,
                'review_strategy': 'full_auto_auto_approved',
            }
        try:
            with transaction.atomic():
                project = NovelProject.objects.select_for_update().get(
                    id=project_id, user=request.user, is_deleted=False
                )
                chapter, _ = Chapter.objects.update_or_create(
                    project=project,
                    chapter_number=chapter_number,
                    defaults={
                        'title': chapter_title,
                        'raw_content': content,
                        'final_content': content,
                        'word_count': word_count,
                        'generation_meta': generation_meta,
                        'context_snapshot': context_snapshot,
                        'summary': '',
                        'open_threads': [],
                        'consistency_status': {},
                        'status': 'draft',
                        'generated_at': timezone.now(),
                        'is_deleted': False,
                    },
                )
                refresh_chapter_workflow_assets(project, chapter, content)
                review = sync_chapter_review(
                    chapter,
                    reviewer=request.user,
                    refresh_ai=True,
                    reset_status=True,
                )
                if full_auto_mode:
                    review.status = 'approved'
                    review.reviewer = request.user
                    review.review_notes = review.review_notes or FULL_AUTO_REVIEW_NOTE
                    review.save(update_fields=[
                        'status',
                        'reviewer',
                        'review_notes',
                        'updated_at',
                    ])
                    chapter.reviewed_at = timezone.now()
                    chapter.save(update_fields=['reviewed_at', 'updated_at'])
                chapter.review_record = review
                project.current_chapter = max(project.current_chapter, chapter_number)
                project.last_update_at = timezone.now()
                project.save(update_fields=['current_chapter', 'last_update_at', 'updated_at'])
        except NovelProject.DoesNotExist:
            return Response({'error': 'Project not found'}, status=status.HTTP_404_NOT_FOUND)

        return Response(ChapterSerializer(chapter).data, status=status.HTTP_201_CREATED)
