# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('metric_type', models.CharField(choices=[('generation', '生成统计'), ('cost', '成本统计'), ('performance', '性能统计')], max_length=20, verbose_name='指标类型')),
                ('metric_data', models.JSONField(default=dict, verbose_name='指标数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '统计数据',
                'verbose_name_plural': '统计数据',
                'db_table': 'stats',
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('date', 'metric_type')},
            },
        ),
    ]
