# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('crawl_ideas', '采集创意'), ('generate_outline', '生成大纲'), ('generate_chapter', '生成章节'), ('publish_chapter', '发布章节')], max_length=50, verbose_name='任务类型')),
                ('related_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联对象类型')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象 ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('retry', '重试中')], default='pending', max_length=20, verbose_name='状态')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery 任务 ID')),
                ('params', models.JSONField(default=dict, verbose_name='任务参数')),
                ('result', models.JSONField(blank=True, default=dict, null=True, verbose_name='任务结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='task_status_b8a06a_idx'), models.Index(fields=['celery_task_id'], name='task_celery__53913c_idx')],
            },
        ),
    ]
