# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='章节序号')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='章节标题')),
                ('raw_content', models.TextField(blank=True, null=True, verbose_name='AI 原始内容')),
                ('final_content', models.TextField(blank=True, null=True, verbose_name='人工审核后内容')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('generation_prompt', models.TextField(blank=True, null=True, verbose_name='生成 Prompt')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('pending_review', '待审核'), ('approved', '已审核'), ('published', '已发布'), ('failed', '生成失败')], default='generating', max_length=20, verbose_name='状态')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('tomato_chapter_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='番茄小说章节 ID')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'chapter',
                'ordering': ['project', 'chapter_number'],
            },
        ),
    ]
