# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_providers', '0001_initial'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='llm_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='llm_providers.llmprovider', verbose_name='使用的 LLM 服务'),
        ),
    ]
