# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        ('chapters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novelproject', verbose_name='所属项目'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['status', '-generated_at'], name='chapter_status_1150c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('project', 'chapter_number')},
        ),
    ]
