# Generated by Django 4.2.11 on 2026-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
