# Generated by Django 4.2.11 on 2026-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_chapter_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('generating', '生成中'), ('draft', '草稿'), ('published', '已发布'), ('failed', '生成失败')], default='generating', max_length=20, verbose_name='状态'),
        ),
    ]
