# Generated by Django 4.2.11 on 2026-04-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_alter_draftsetting_setting_type_and_more'),
        ('chapters', '0005_chapter_status_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='生成时上下文快照'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='generation_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='生成元数据'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='open_threads',
            field=models.JSONField(blank=True, default=list, verbose_name='开放线索'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='章节摘要'),
        ),
        migrations.CreateModel(
            name='ChapterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('key_events', models.JSONField(blank=True, default=list, verbose_name='关键事件')),
                ('open_threads', models.JSONField(blank=True, default=list, verbose_name='开放线索')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_record', to='chapters.chapter', verbose_name='所属章节')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_summaries', to='novels.novelproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '章节摘要',
                'verbose_name_plural': '章节摘要',
                'db_table': 'chapter_summary',
                'ordering': ['chapter__chapter_number'],
                'indexes': [models.Index(fields=['project', 'updated_at'], name='chapter_sum_project_262a1d_idx')],
            },
        ),
    ]
