# Generated by Django 4.2.11 on 2026-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_chapter_context_snapshot_chapter_generation_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='consistency_status',
            field=models.JSONField(blank=True, default=dict, verbose_name='一致性状态'),
        ),
    ]
