# Generated by Django 4.2.11 on 2026-04-20 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_chapter_consistency_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待阅'), ('approved', '已定稿'), ('revise', '需修订')], default='pending', max_length=20, verbose_name='审阅状态')),
                ('review_notes', models.TextField(blank=True, verbose_name='审阅意见')),
                ('ai_review', models.TextField(blank=True, verbose_name='AI 审读建议')),
                ('ai_action_items', models.JSONField(blank=True, default=list, verbose_name='AI 审读动作项')),
                ('modification_rate', models.IntegerField(default=0, verbose_name='预估修改率')),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='AI 建议生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_record', to='chapters.chapter', verbose_name='所属章节')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_reviews', to='novels.novelproject', verbose_name='所属项目')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审阅人')),
            ],
            options={
                'verbose_name': '章节审阅',
                'verbose_name_plural': '章节审阅',
                'db_table': 'chapter_review',
                'ordering': ['chapter__chapter_number'],
            },
        ),
        migrations.AddIndex(
            model_name='chapterreview',
            index=models.Index(fields=['project', 'status'], name='chapter_rev_project_4f95f4_idx'),
        ),
    ]
