# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspirations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('genre', models.CharField(max_length=50, verbose_name='分类')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('outline', models.TextField(blank=True, null=True, verbose_name='大纲')),
                ('ai_prompt_template', models.TextField(blank=True, null=True, verbose_name='章节生成 Prompt 模板')),
                ('status', models.CharField(choices=[('active', '活跃'), ('paused', '暂停'), ('completed', '完结'), ('abandoned', '废弃')], default='active', max_length=20, verbose_name='状态')),
                ('target_chapters', models.IntegerField(default=100, verbose_name='目标章节数')),
                ('current_chapter', models.IntegerField(default=0, verbose_name='当前章节数')),
                ('update_frequency', models.IntegerField(default=1, verbose_name='每日更新章节数')),
                ('last_update_at', models.DateTimeField(blank=True, null=True, verbose_name='最后更新时间')),
                ('tomato_book_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='番茄小说书籍 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('inspiration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', to='inspirations.inspiration', verbose_name='创意来源')),
            ],
            options={
                'verbose_name': '小说项目',
                'verbose_name_plural': '小说项目',
                'db_table': 'novel_project',
                'ordering': ['-created_at'],
            },
        ),
    ]
