# Generated by Django 4.2.11 on 2026-04-03 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novelproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='novelproject',
            index=models.Index(fields=['user', 'status'], name='novel_proje_user_id_7279e0_idx'),
        ),
        migrations.AddIndex(
            model_name='novelproject',
            index=models.Index(fields=['status', 'last_update_at'], name='novel_proje_status_821843_idx'),
        ),
    ]
