# Generated by Django 4.2.11 on 2026-04-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelproject',
            name='auto_generation_enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用自动生成'),
        ),
        migrations.AddField(
            model_name='novelproject',
            name='generation_schedule',
            field=models.CharField(choices=[('daily', '每天'), ('every_2_days', '每2天'), ('weekly', '每周')], default='daily', max_length=20, verbose_name='生成计划'),
        ),
        migrations.AddField(
            model_name='novelproject',
            name='next_generation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次生成时间'),
        ),
    ]
