# Generated by Django 4.2.11 on 2026-04-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_novelproject_auto_generation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelproject',
            name='wizard_completed',
            field=models.BooleanField(default=False, verbose_name='向导是否完成'),
        ),
        migrations.AddField(
            model_name='novelproject',
            name='wizard_step',
            field=models.IntegerField(default=0, verbose_name='向导当前步骤'),
        ),
        migrations.CreateModel(
            name='NovelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('worldview', '世界观'), ('characters', '人物'), ('map', '地图'), ('storyline', '故事线'), ('plot_arc', '情节弧')], max_length=20, verbose_name='设定类型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='详细内容')),
                ('structured_data', models.JSONField(blank=True, default=dict, verbose_name='结构化数据')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='是否 AI 生成')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='novels.novelproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '小说设定',
                'verbose_name_plural': '小说设定',
                'db_table': 'novel_setting',
                'ordering': ['order'],
                'unique_together': {('project', 'setting_type')},
            },
        ),
    ]
