# Generated by Django 4.2.11 on 2026-04-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_novelproject_wizard_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelsetting',
            name='setting_type',
            field=models.CharField(choices=[('worldview', '世界观'), ('characters', '人物'), ('map', '地图'), ('storyline', '故事线'), ('plot_arc', '情节弧'), ('opening', '开始'), ('dimension_framework', '维度框架'), ('main_characters', '主要角色'), ('map_system', '地图系统'), ('main_sub_plots', '主线支线'), ('plot_extraction', '剧情抽离')], max_length=30, verbose_name='设定类型'),
        ),
    ]
