# Generated by Django 4.2.11 on 2026-04-13 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0005_alter_novelsetting_setting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration', models.TextField(verbose_name='灵感输入')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='暂定书名')),
                ('genre', models.CharField(blank=True, default='未分类', max_length=50, verbose_name='分类')),
                ('current_step', models.IntegerField(default=0, verbose_name='当前步骤')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成转化')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='novels.novelproject', verbose_name='转化后的项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '小说草稿',
                'verbose_name_plural': '小说草稿',
                'db_table': 'novel_draft',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('worldview', '世界观'), ('characters', '人物'), ('map', '地图'), ('storyline', '故事线'), ('plot_arc', '情节弧'), ('opening', '开始'), ('dimension_framework', '维度框架'), ('main_characters', '主要角色'), ('map_system', '地图系统'), ('main_sub_plots', '主线支线'), ('plot_extraction', '剧情抽离')], max_length=30, verbose_name='设定类型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='详细内容')),
                ('structured_data', models.JSONField(blank=True, default=dict, verbose_name='结构化数据')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='是否 AI 生成')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='novels.noveldraft', verbose_name='所属草稿')),
            ],
            options={
                'verbose_name': '草稿设定',
                'verbose_name_plural': '草稿设定',
                'db_table': 'novel_draft_setting',
                'ordering': ['order'],
                'unique_together': {('draft', 'setting_type')},
            },
        ),
    ]
