# Generated by Django 4.2.11 on 2026-04-13 14:12

from django.db import migrations, models


REMOVED_TYPES = [
    'dimension_framework',
    'main_characters',
    'map_system',
    'main_sub_plots',
    'plot_extraction',
]


def cleanup_removed_setting_types(apps, schema_editor):
    """Delete rows with removed setting types and cap wizard steps to 6."""
    NovelSetting = apps.get_model('novels', 'NovelSetting')
    DraftSetting = apps.get_model('novels', 'DraftSetting')
    NovelProject = apps.get_model('novels', 'NovelProject')
    NovelDraft = apps.get_model('novels', 'NovelDraft')

    NovelSetting.objects.filter(setting_type__in=REMOVED_TYPES).delete()
    DraftSetting.objects.filter(setting_type__in=REMOVED_TYPES).delete()
    NovelProject.objects.filter(wizard_step__gt=6).update(wizard_step=6)
    NovelDraft.objects.filter(current_step__gt=6).update(current_step=6)


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_noveldraft_draftsetting'),
    ]

    operations = [
        migrations.RunPython(
            cleanup_removed_setting_types,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='draftsetting',
            name='setting_type',
            field=models.CharField(choices=[('worldview', '世界观'), ('characters', '人物'), ('map', '地图'), ('storyline', '故事线'), ('plot_arc', '情节弧'), ('opening', '开始')], max_length=30, verbose_name='设定类型'),
        ),
        migrations.AlterField(
            model_name='novelsetting',
            name='setting_type',
            field=models.CharField(choices=[('worldview', '世界观'), ('characters', '人物'), ('map', '地图'), ('storyline', '故事线'), ('plot_arc', '情节弧'), ('opening', '开始')], max_length=30, verbose_name='设定类型'),
        ),
    ]
