# Generated by Django 4.2.11 on 2026-04-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_chapter_consistency_status'),
        ('novels', '0007_alter_draftsetting_setting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsetting',
            name='source',
            field=models.CharField(choices=[('wizard', '向导'), ('manual', '手动'), ('regenerated', '重新生成'), ('imported', '导入')], default='wizard', max_length=20, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='novelsetting',
            name='source',
            field=models.CharField(choices=[('wizard', '向导'), ('manual', '手动'), ('regenerated', '重新生成'), ('imported', '导入')], default='manual', max_length=20, verbose_name='来源'),
        ),
        migrations.CreateModel(
            name='Storyline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('storyline_type', models.CharField(choices=[('main', '主线'), ('subplot', '支线'), ('character', '角色线'), ('world', '世界线')], default='main', max_length=20, verbose_name='故事线类型')),
                ('status', models.CharField(choices=[('planned', '规划中'), ('active', '进行中'), ('resolved', '已完成'), ('paused', '暂停')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('estimated_chapter_start', models.IntegerField(default=1, verbose_name='预计起始章节')),
                ('estimated_chapter_end', models.IntegerField(default=0, verbose_name='预计结束章节')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storylines', to='novels.novelproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '故事线',
                'verbose_name_plural': '故事线',
                'db_table': 'storyline',
                'ordering': ['-priority', 'estimated_chapter_start', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlotArcPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(default=1, verbose_name='章节号')),
                ('point_type', models.CharField(choices=[('opening', '开篇'), ('setup', '铺垫'), ('turning', '转折'), ('climax', '高潮'), ('resolution', '收束')], default='setup', max_length=20, verbose_name='节点类型')),
                ('tension_level', models.IntegerField(default=50, verbose_name='张力等级')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_arc_points', to='novels.novelproject', verbose_name='所属项目')),
                ('related_storyline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plot_points', to='novels.storyline', verbose_name='关联故事线')),
            ],
            options={
                'verbose_name': '情节点',
                'verbose_name_plural': '情节点',
                'db_table': 'plot_arc_point',
                'ordering': ['chapter_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='主语')),
                ('predicate', models.CharField(max_length=100, verbose_name='谓语')),
                ('object', models.CharField(max_length=255, verbose_name='宾语')),
                ('source_excerpt', models.TextField(blank=True, verbose_name='来源片段')),
                ('confidence', models.FloatField(default=0.7, verbose_name='置信度')),
                ('status', models.CharField(choices=[('confirmed', '已确认'), ('draft', '待确认'), ('conflict', '冲突')], default='confirmed', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_facts', to='chapters.chapter', verbose_name='来源章节')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_facts', to='novels.novelproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '知识事实',
                'verbose_name_plural': '知识事实',
                'db_table': 'knowledge_fact',
                'ordering': ['-updated_at', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='ForeshadowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('expected_payoff_chapter', models.IntegerField(default=0, verbose_name='预期回收章节')),
                ('status', models.CharField(choices=[('open', '已埋设'), ('hinted', '已提示'), ('resolved', '已回收'), ('abandoned', '已废弃')], default='open', max_length=20, verbose_name='状态')),
                ('related_character', models.CharField(blank=True, max_length=200, verbose_name='关联角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('introduced_in_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_foreshadow_items', to='chapters.chapter', verbose_name='引入章节')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreshadow_items', to='novels.novelproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '伏笔项',
                'verbose_name_plural': '伏笔项',
                'db_table': 'foreshadow_item',
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('project', '项目基线'), ('character_voice', '角色声音'), ('chapter_analysis', '章节分析')], default='project', max_length=30, verbose_name='画像类型')),
                ('content', models.TextField(blank=True, verbose_name='画像内容')),
                ('structured_data', models.JSONField(blank=True, default=dict, verbose_name='结构化画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_profiles', to='novels.novelproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '风格画像',
                'verbose_name_plural': '风格画像',
                'db_table': 'style_profile',
                'ordering': ['profile_type', '-updated_at'],
                'indexes': [models.Index(fields=['project', 'profile_type'], name='style_profi_project_d9e809_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='storyline',
            index=models.Index(fields=['project', 'status'], name='storyline_project_ac90db_idx'),
        ),
        migrations.AddIndex(
            model_name='plotarcpoint',
            index=models.Index(fields=['project', 'chapter_number'], name='plot_arc_po_project_1827a8_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['project', 'status'], name='knowledge_f_project_4deef2_idx'),
        ),
        migrations.AddIndex(
            model_name='foreshadowitem',
            index=models.Index(fields=['project', 'status'], name='foreshadow__project_ec10a3_idx'),
        ),
    ]
